apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 5000        # Service port inside cluster
      targetPort: 5000  # Container port