apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: frontend-service
  ports:
    - name: http
      port: 80        # Service port inside cluster
      targetPort: 80  # Container port
